# Generated by Django 3.1.7 on 2021-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='content',
        ),
        migrations.AddField(
            model_name='work',
            name='concept',
            field=models.TextField(null=True, verbose_name='Concepto del Proyecto'),
        ),
        migrations.AddField(
            model_name='work',
            name='development',
            field=models.TextField(null=True, verbose_name='Desarrollo del proyecto'),
        ),
        migrations.AddField(
            model_name='work',
            name='fecha',
            field=models.CharField(max_length=50, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='work',
            name='fullpage1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Primera imagen de la web'),
        ),
        migrations.AddField(
            model_name='work',
            name='fullpage2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Segunda imagen de la web'),
        ),
        migrations.AddField(
            model_name='work',
            name='mockup',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Mockup'),
        ),
    ]
