# Generated by Django 3.1.7 on 2021-04-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210416_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(null=True, verbose_name='Url del sitio web'),
        ),
    ]
