# Generated by Django 3.1.7 on 2021-04-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_work_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='fullpage1',
            new_name='page1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='fullpage2',
            new_name='page2',
        ),
    ]
