# Generated by Django 3.1.7 on 2021-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210423_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
