# Generated by Django 3.1.7 on 2021-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_work_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='number',
        ),
        migrations.AddField(
            model_name='work',
            name='Odd',
            field=models.BooleanField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
