# Generated by Django 3.1.7 on 2021-04-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210423_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Odd',
            new_name='odd',
        ),
    ]
