# Generated by Django 3.1.7 on 2021-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210423_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='odd',
            field=models.BooleanField(blank=True, null=True, verbose_name='Impar'),
        ),
    ]
