# Generated by Django 3.1.7 on 2021-04-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_work_even'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('id',), 'verbose_name': 'trabajo', 'verbose_name_plural': 'trabajos'},
        ),
    ]
